apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
  {{- include "labels.common" . | nindent 4 }}
webhooks:
  - name: azureconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azureconfig
      caBundle: Cg==
    rules:
      - apiGroups: ["provider.giantswarm.io"]
        resources:
          - "azureconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azureclusterconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azureclusterconfig
      caBundle: Cg==
    rules:
      - apiGroups: ["core.giantswarm.io"]
        resources:
          - "azureclusterconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azuremachinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azuremachinepoolcreate
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azuremachinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azuremachinepoolupdate
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
